### ISSUE TITLE
Add slides

### ISSUE THREAD

**Issue by amirhmk** [quentinv72/MathVR#19]
Create a slide component with text on it

**Comment by quentinv72** [comment]
Create a slide component with text on it

**Comment by quentinv72** [comment]
Need to add a transition from slides to animation

**Comment by quentinv72** [comment]
> Need to add a transition from slides to animation

Transition have been added.
Furthermore, the code has been refactored, to break it down a bit more and make more readable (cf. scene.html).

**Comment by quentinv72** [comment]
Need to add slide content
